// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwS3MiL1PIJ5t-nnaEYVuu_Xm-l5mu5I',
    appId: '1:991252874033:web:4ab77daf20bd77cb442610',
    messagingSenderId: '991252874033',
    projectId: 'myflutterapp-41b3f',
    authDomain: 'myflutterapp-41b3f.firebaseapp.com',
    storageBucket: 'myflutterapp-41b3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ZgzkeB0d5XlPJwhYnyv2Ko3Iyj_LAz8',
    appId: '1:991252874033:android:239772cc487b1dd6442610',
    messagingSenderId: '991252874033',
    projectId: 'myflutterapp-41b3f',
    storageBucket: 'myflutterapp-41b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCUrP238Pg-fqc-W-DjBWukETjJYbJv9o',
    appId: '1:991252874033:ios:277e87e08408ec20442610',
    messagingSenderId: '991252874033',
    projectId: 'myflutterapp-41b3f',
    storageBucket: 'myflutterapp-41b3f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCUrP238Pg-fqc-W-DjBWukETjJYbJv9o',
    appId: '1:991252874033:ios:277e87e08408ec20442610',
    messagingSenderId: '991252874033',
    projectId: 'myflutterapp-41b3f',
    storageBucket: 'myflutterapp-41b3f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkwS3MiL1PIJ5t-nnaEYVuu_Xm-l5mu5I',
    appId: '1:991252874033:web:72a450ff55a8eb80442610',
    messagingSenderId: '991252874033',
    projectId: 'myflutterapp-41b3f',
    authDomain: 'myflutterapp-41b3f.firebaseapp.com',
    storageBucket: 'myflutterapp-41b3f.firebasestorage.app',
  );
}
